<a href="https://colab.research.google.com/github/nochwysid/CSE5008-SP/blob/main/MichailSeth_E4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

9 Numpy  

Generate matrices $A$, with random Gaussian entries, $B$, a Toeplitz matrix, where $A ∈ R
^{n×m}$ and $B ∈ R^{m×m}$, for $n = 200$, $m = 500$. 

In [102]:
import numpy as np

A = np.random.normal(0,1,(200,500))
A

array([[ 0.60084903,  0.39849743,  1.48081858, ..., -1.44750238,
         0.05849323,  1.42704828],
       [-0.36171614,  1.06313077,  1.73478097, ...,  0.76008766,
         1.10062101,  1.02959258],
       [ 1.6346381 , -0.03788837,  1.10256113, ...,  0.14106723,
         0.86356426, -0.77183582],
       ...,
       [-0.96690652,  0.06419198, -0.41411289, ..., -0.50851269,
        -0.4888217 , -0.73481653],
       [-0.31684654, -0.79651231,  1.7629482 , ...,  0.09982181,
         0.44387031,  1.98754615],
       [-0.37618052,  0.9294823 , -0.08251486, ...,  1.37353563,
         0.44946169, -0.19115459]])

In [103]:
B = np.array([[i-j for i in range(500)] for j in range(500)])
B

array([[   0,    1,    2, ...,  497,  498,  499],
       [  -1,    0,    1, ...,  496,  497,  498],
       [  -2,   -1,    0, ...,  495,  496,  497],
       ...,
       [-497, -496, -495, ...,    0,    1,    2],
       [-498, -497, -496, ...,   -1,    0,    1],
       [-499, -498, -497, ...,   -2,   -1,    0]])

 
Exercise 9.1: Matrix operations  
Calculate $A + A$,&nbsp; $AA^{T}$,&nbsp; $A^{T}A$ &nbsp;and $AB$. Write a function that computes $A(B − λI)$ for any $λ$.

In [104]:
# A + A
aplus = np.add(A,A)
aplus

array([[ 1.20169806,  0.79699487,  2.96163717, ..., -2.89500475,
         0.11698647,  2.85409656],
       [-0.72343228,  2.12626153,  3.46956195, ...,  1.52017532,
         2.20124201,  2.05918516],
       [ 3.2692762 , -0.07577673,  2.20512226, ...,  0.28213445,
         1.72712853, -1.54367164],
       ...,
       [-1.93381304,  0.12838396, -0.82822578, ..., -1.01702538,
        -0.9776434 , -1.46963306],
       [-0.63369309, -1.59302462,  3.5258964 , ...,  0.19964363,
         0.88774062,  3.97509231],
       [-0.75236103,  1.8589646 , -0.16502972, ...,  2.74707126,
         0.89892338, -0.38230918]])

In [105]:
# AA^T
aat = np.dot(A,A.T)
aat

array([[474.57357229,  -5.23403558, -25.48552111, ...,  -8.75349459,
        -22.02000176,   1.04185997],
       [ -5.23403558, 478.46845653,  25.35604146, ..., -39.2481331 ,
         11.06748411,  -7.76313728],
       [-25.48552111,  25.35604146, 478.95107607, ..., -22.9220887 ,
         18.51469924,   5.31966138],
       ...,
       [ -8.75349459, -39.2481331 , -22.9220887 , ..., 496.07313366,
          3.64756249,  14.97364728],
       [-22.02000176,  11.06748411,  18.51469924, ...,   3.64756249,
        502.21882601,  21.46071395],
       [  1.04185997,  -7.76313728,   5.31966138, ...,  14.97364728,
         21.46071395, 520.08195455]])

In [106]:
# A^TA
ata = np.dot(A.T,A)
ata

array([[221.11245369, -14.2539357 , -19.65105847, ..., -20.78890125,
         15.63369352, -34.08219061],
       [-14.2539357 , 191.77177315,  -9.1324877 , ..., -12.59032822,
         -1.29292042,  43.56329398],
       [-19.65105847,  -9.1324877 , 223.43568318, ...,  -1.07822693,
         25.38224723,  -0.44399487],
       ...,
       [-20.78890125, -12.59032822,  -1.07822693, ..., 188.7060188 ,
          3.62668688,  -9.81406659],
       [ 15.63369352,  -1.29292042,  25.38224723, ...,   3.62668688,
        178.76300698, -15.30435022],
       [-34.08219061,  43.56329398,  -0.44399487, ...,  -9.81406659,
        -15.30435022, 203.6825024 ]])

In [107]:
# AB (BA not possible, but BA^T is)
ab = np.dot(A,B)
ab

array([[ 4861.14763954,  4852.27326243,  4843.39888532, ...,
          450.58221642,   441.70783931,   432.8334622 ],
       [-8987.22947879, -8966.68050354, -8946.1315283 , ...,
         1225.61121661,  1246.16019186,  1266.7091671 ],
       [ 2254.73528675,  2270.14334727,  2285.55140779, ...,
         9912.5413643 ,  9927.94942482,  9943.35748534],
       ...,
       [ -598.08870898,  -597.08789724,  -596.0870855 , ...,
         -100.68527526,   -99.68446352,   -98.68365178],
       [10441.7004254 , 10406.28150131, 10370.86257722, ...,
        -7161.50484798, -7196.92377208, -7232.34269617],
       [ 3529.04085276,  3508.66465811,  3488.28846346, ...,
        -6597.92788866, -6618.30408331, -6638.68027796]])

In [109]:
# A(B-lI) function
def abi(a,b,l):
  lI = l*np.eye(b.shape[0])
  abi = np.dot(a,(np.subtract(b,lI)) )
  return abi
print(abi(A,B,3))

[[ 4859.34509244  4851.07777013  4838.95642957 ...   454.92472354
    441.5323596    428.55231735]
 [-8986.14433037 -8969.86989584 -8951.33587123 ...  1223.33095363
   1242.85832884  1263.62038936]
 [ 2249.83137246  2270.25701236  2282.2437244  ...  9912.11816262
   9925.35873203  9945.67299279]
 ...
 [ -595.18798941  -597.28047318  -594.84474684 ...   -99.1597372
    -98.21799842   -96.47920219]
 [10442.65096504 10408.67103825 10365.57373262 ... -7161.80431343
  -7198.25538301 -7238.30533463]
 [ 3530.16939431  3505.87621121  3488.53600803 ... -6602.04849556
  -6619.65246839 -6638.1068142 ]]


Exercise 9.2: Solving a linear system  
Generate a vector $b$ with m entries and solve $Bx = b$.

In [4]:
b = np.arange(0,4).T + 1
g  =  np.arange(0,16).reshape(4,4) - np.eye(4)
s = np.linalg.solve(g,b)
print('B =', g)
print('b =', b)
print('x =', s)

B = [[-1.  1.  2.  3.]
 [ 4.  4.  6.  7.]
 [ 8.  9.  9. 11.]
 [12. 13. 14. 14.]]
b = [1 2 3 4]
x = [-0.08256881  0.01834862  0.11926606  0.22018349]


Exercise 9.3: Norms  
Compute the Frobenius norm of $A$: $\|A\|_F$ and the infinity norm of $B$: $\|B\|_∞$. Also find the largest and
smallest singular values of $B$.

In [110]:
froA = np.linalg.norm(A,'fro')
froA

314.9290175174507

In [111]:
froB = np.linalg.norm(B,np.inf)
froB

124750.0

In [112]:
maxsvdB = np.linalg.norm(B,2)
maxsvdB

72168.6393109916

Exercise 9.4: Power iteration  
Generate a matrix $Z$, $n × n$, with Gaussian entries, and use the power iteration to find the largest
eigenvalue and corresponding eigenvector of $Z$. How many iterations are needed till convergence?  
Optional: use the time.clock() method to compare computation time when varying $n$.

In [100]:
import time
import numpy as np
start = time.time_ns()
n = 5
k = 0
Z = np.random.normal(0,2,(n,n))
e = np.random.normal(0,2,(n))
count = 0
lambda_1 = 0
while count < 10:
  prevprev = prev.copy()
  prev = e.copy()
  
  e = np.dot(Z,e)
  e =  e / e.max()
  lambda_1 = abs(e).max()
  k += 1
  #print(abs(np.sum(e - prevprev)))
  if abs(np.sum(e - prevprev)) < 1E-10 :
    count += 1

print('lambda:', lambda_1,'\n')
print('It took {} iterations to converge'.format(k-count))
print('\n',(Z*e)[0]/e[0],'\n')
[val, vec] = np.linalg.eigh(Z)
lval = list(abs(val))
idx = lval.index(max(lval))
end = time.time_ns() - start

print('time :{} ms'.format(end/1E6))
print('eigenvector : \n\t',list(vec[:,idx]))
print('largest eigenvalue :\n\t', lval[idx])


lambda: 1.90483643239864 

It took 96 iterations to converge

 [-1.76453576  8.30822822 -0.20227535 -3.74698036  2.33224793] 

time :8.587888 ms
eigenvector : 
	 [-0.2526055395777507, 0.8011870627360018, 0.3331653124989439, 0.10025604949636552, 0.4162202913914156]
largest eigenvalue :
	 6.646015221775013


Exercise 9.6: Nearest neighbor  
Write a function that takes a value $z$ and an array $A$ and finds the element in $A$ that is closest to $z$. The function should return the closest value, not index.  
Hint: Use the built-in functionality of Numpy rather than writing code to find this value manually. In
particular, use brackets and argmin.

In [101]:
z = 27
A = 2*np.arange(25).reshape(5,5)
A = 2*np.random.randint(0,50,(5,5))
print('A:\n',A)
def thenearestneighborinthehood(mat,val):
  #ndx = np.where( abs(mat -val) < 2 )
  tmat = abs(mat - val)
  #print(tmat)
  arg = np.argmin(tmat)
  c = arg%(tmat.shape[1] )
  r = (int)((arg-c)/tmat.shape[1])
  print('r, c:',r,c)
  print('Nearest number:',A[r,c])
  
  neighbor = A[r,c]
  return neighbor, r, c
n,r,c = thenearestneighborinthehood(A,z)
print('Number nearest to {} is {}, located at ({},{})'.format(z,n,r,c))

A:
 [[44 52 86 20  0]
 [94 54 78 36  6]
 [24 64 76 32 96]
 [98 62 46 24 14]
 [84 32 44 14 50]]
r, c: 2 0
Nearest number: 24
Number nearest to 27 is 24, located at (2,0)
