<a href="https://colab.research.google.com/github/nochwysid/CSE5008-SP/blob/main/Tips_Tricks_and_Extras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import numpy.random as rnd
np.set_printoptions(precision=4, linewidth=199)
import scipy as sp
import matplotlib.pyplot as plt

[Numpy row_stack](https://numpy.org/devdocs/reference/generated/numpy.row_stack.html?highlight=row_stack#numpy.row_stack)  

[Numpy LinAlg](https://numpy.org/doc/stable/reference/routines.linalg.html)

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2 to 4, not 5
x[2:5]

array([2, 3, 4])

In [ ]:
#all but last 7
x[:-7]

array([0, 1, 2])

In [ ]:
#x[start:stop:skip]
x[1:7:2]

array([1, 3, 5])

In [ ]:
y = np.arange(35).reshape(5,7)
y

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [ ]:
y[1:5:2,::3]

array([[ 7, 10, 13],
       [21, 24, 27]])

In [ ]:
y[1:5:1,::2]

array([[ 7,  9, 11, 13],
       [14, 16, 18, 20],
       [21, 23, 25, 27],
       [28, 30, 32, 34]])

In [ ]:
z = np.zeros((7,7))
#using an array for indexing
idx = np.arange(1,7)
idx = np.array([1,2,4,6])
z[idx,idx-1] = 0.6
z


array([[0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0.6, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.6, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.6, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.6, 0. ]])

In [ ]:
def transition_matrix(n):
    """look at all the thing needed to get this fancy matrix"""
    mc = np.zeros((n,n))
    m = np.arange(1,n)
    mc[m,m-1] = 0.6
    mc[m-1,m] = 0.3
    mc[0,0] = 0.3
    mc[0,:] += 0.1
    mc[0,n-1] = 0
    mc[n-1,n-1] = 1
    mc[n-2,n-1] = 0
    
    return mc
tm = transition_matrix(10)
tm

array([[0.4, 0.4, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0. ],
       [0.6, 0. , 0.3, 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0.6, 0. , 0.3, 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0.6, 0. , 0.3, 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.6, 0. , 0.3, 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0.6, 0. , 0.3, 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0.6, 0. , 0.3, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0.6, 0. , 0.3, 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.6, 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0.6, 1. ]])

In [ ]:
print(tm)

[[0.4 0.4 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0. ]
 [0.6 0.  0.3 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.6 0.  0.3 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.6 0.  0.3 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.6 0.  0.3 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.6 0.  0.3 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.6 0.  0.3 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.6 0.  0.3 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.6 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.6 1. ]]


In [ ]:
def cube(x):
  """DocString provides info about a func by calling 'help(funcname)', i.e. 'help(cube)' will retrun this docstring"""
  cube = lambda x: x*x*x
  return cube
print (cube(3))
help(cube)

In [ ]:
def funk(x, a=1, b=3):
  """having defaults specified, basically, allows 3 funks in one"""
  return x + a - b

print (funk(2) )# 0
print (funk(5, 2)) # 4
print (funk(3, b=0)) # 4

In [ ]:
def function1(x):
  def function2(y):
    print y + 2
    return y + 2
  return 3 * function2(x)
a = function1(2) # 4
print (a) # 12
b = function2(2.5) # error: undefined name

In [ ]:
def f1():
  """DocString for f1, callable everywhere after definition"""
  def f2():
    """DocString for f2, callable only inside f1"""
    pass
  help(f2)
help(f1)


In [ ]:
len(xs)
xs.append(x)
xs.count(x)
xs.insert(i, x)
xs.sort() 
# and 
sorted(xs)#: what’s the difference?
xs.remove(x)
xs.pop()
# or 
xs.pop(i)
x in xs
dir([])

In [ ]:
"""loop over both element and index at the same time."""
myList = [1, 2, 4]
for index, elem in enumerate(myList):
  print( "{0} {1}".format(index, elem))
# 0) 1
# 1) 2
# 2) 4

""" apply a function to all elements of a list using map"""
l = range(4)
print (map(lambda x: x*x*x, l))
# [0, 1, 8, 27]

"""to filter elements of a list """
l = range(8)
print( filter(lambda x: x % 2 == 0, l))
# [0, 2, 4, 6]

"""list comprehensions are often more readable and concise than using map or filter"""
print( [i**2 for i in range(5)])
# [0, 1, 4, 9, 16]
ints = [1, 3, 10]
[i * 2 for i in ints]
# [2, 6, 20]
[[i, j] for i in ints for j in ints if i != j]
# [[1, 3], [1, 10], [3, 1], [3, 10], [10, 1], [10, 3]]
[(x, y) for x in range(3) for y in range(x+1)]

0 1
1 2
2 4
[0, 1, 4, 9, 16]


[(0, 0), (1, 0), (1, 1), (2, 0), (2, 1), (2, 2)]

In [ ]:
#subplot(rows,cols,1<num<rows*cols)
plt.subplot(3, 1, 2)

An aside, to ensure mean zero variance one

In [ ]:
c = np.random.normal(0,1,1000) 
print(' before: average ={}, mean ={}, sum ={}, max ={}'.format(np.average(c),np.mean(c),np.sum(c),np.amax(c)))
c -= np.average(c)
print('during average ={}, mean ={}, sum ={}, max ={}'.format(np.average(c),np.mean(c),np.sum(c),np.amax(c)))
c[np.argmax(c)] -= np.sum(c)
c /= np.amax(c)
print('after:average ={}, mean ={}, sum ={}, max ={}'.format(np.average(c),np.mean(c),np.sum(c),np.amax(c)))

print(c)


Another aside, regarding finding indices of max value of a matrix

In [ ]:
F = np.random.normal(0,1,size=(10,10))
G = np.multiply(F,np.eye(F.shape[0]))

max1 = np.amax(G)
idx = np.where(G == np.amax(G))
G[idx[0],idx[1]] = 0
print(G,idx)

max2 = np.amax(G)
idx = np.where(G == np.amax(G))
G[idx[0],idx[1]] -= max2
print(G,idx)

max3 = np.amax(G)
idx = np.where(G == np.amax(G))
G[idx[0],idx[1]] -= max3
print(G,idx)

print('largest {}, second largest {}, third {}'.format(max1,max2,max3))

[SciPy Stats Portal](https://docs.scipy.org/doc/scipy/reference/stats.html)

In [ ]:
from scipy import linalg
n = 100
p = 0.43
C = np.random.choice([0,1], size=(n,n), p=[1-p,p])
linalg.svdvals(C).max()

Ridge Regression  
The ridge regression estimator is the solution to the following modified least squares
optimization problem for some value of $λ > 0$.  
$$\hat{β}_{ridge} = \text{arg min}_b \{ {||y − Xb||^2_2 + λ||b||^2_2} \}$$

Why the ridge penalty?
1. The equation shrinks the coefficients towards zero, adding some bias but reducing
the variance of the estimator.
2. Using the $ℓ_2$-norm keeps the equation rotationally invariant.
3. Ridge regression has an analytical solution.

To see this write the criterion as a matrix equation:
$$(y − Xb)^T(y − Xb) + λb^Tb = y^Ty + b^TX^TXb − 2y^TXb + λb^Tb$$
<!---\hspace {47.5pt}--->
And take its derivative:
$$\frac{∂}{∂β}(y^Ty + b^TX^TXb − 2y^TXb + λb^Tb)= 2X^TXb − 2X^Ty + 2λb$$

Setting this to zero yields
$$2X^TX\hat{β} + 2λ\hat{β} = 2X^Ty$$  
$$(X^TX + I_pλ)\hat{β} = X^Ty$$  
$$\hspace {135pt}\hat{β} = (X^TX + I_pλ)^{−1}· X^Ty$$

This is a useful analytical form, though as with least squares we would generally not
invert the matrix directly but instead use a stable matrix decomposition.

Computationalissues  
How can we estimate the regression vector using a technique such as ordinary least
squares
$$\hat{β}_{ols} = \text{arg min}_b \left\{ \overset{n}{\underset{i=1}{∑}} (y_i − x^T_ib)^2 \right\} $$  
When we have a dataset size grows larger than the available memory?


At first glance this seems computationally very difficult as we are trying to minimize a
summation with one component per observation.
However, recall that the ordinary least squares solution can be computed by:  
$$\hat{β}_{ols} = (X^TX)^{−1}X^Ty$$  

Now, assume that the data matrix X is broken by rows into K different chunks:  
<!---bmatrix would be better--->
\begin{align}
    X &= \begin{pmatrix}
           X_{B_{1}} \\
           X_{B_{2}} \\
           \vdots \\
           X_{B_{k}}
         \end{pmatrix}
  \end{align}